[dependencies]

[package]
  cjc-version = "0.57.3"
  compile-option = ""
  description = "nothing here"
  link-option = ""
  name = "jwt4cj"
  output-type = "executable"
  override-compile-option = ""
  src-dir = ""
  target-dir = ""
  version = "1.0.0"
  [package.package-configuration]

[ffi]
  [ffi.c]
    [ffi.c.crypto-3-x64]
      path = "C:/Program Files/OpenSSL-Win64/bin"
    [ffi.c.ssl-3-x64]
      path = "C:/Program Files/OpenSSL-Win64/bin"
